[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "maths_py"
version = "1.0.0"

[project.scripts]
egcd_integer = "maths_py.extended_gcd.integer:main"

[project.optional-dependencies]
dev = ["pytest", "pylint", "mypy"]
